version: "3"

networks:
  app-tier:
    driver: bridge

services:
  nuxt:
    build:
      context: .
    restart: unless-stopped
    networks:
      - app-tier

  nginx:
    image: nginx:latest
    restart: unless-stopped
    environment:
      - SERVER_NAME=${SERVER_NAME:-localhost}
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
    depends_on:
      - nuxt
    networks:
      - app-tier
